name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc8382f0fb7c1fce02ba7732c17b54df99ca399e92c2100c0ba845631bdfa76c"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
