name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a759c49579ffbc78cf778c2d19dbb235c47543d978cbdcf442fb668e4641d36f"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
