name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "158701394d6bd62c08fc035d6f66e1e7e6e2c6655bc7d5c842a4bb323f98e844"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
