name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d4f62f2964f28b90ac210fe4cf3d34659df012b6f41d9ce098b502ec863cca3"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
