name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d760afbda974a3e8dfe2ebb6165c07bfb2f88b5d80df01885c81d688d48229b"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
