name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13a56607778b866af2762700042db4ada13293b15f40f77d7c54db47503c9984"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
