name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b6a8c179000631a03356fcbfe00d4654dabed92743632f32e52b862c079aa3a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
