name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e02506f49a247c93ccd75087c1082b6bbc5aa4d7c9ea49042d4727fd3543f49"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
