name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa8e4ae148e65b375d594e2c46f5ae90868d365dc281922201e52219bc52cf8"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
