name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0ccfb42edc0da3f6e31094ac8cf93ebccde5813087bd605677f1394babdb71f"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
