name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac0c155ff7bb6913aceb1f8b91ae0471aab837a092d296bb1d037319b59e3d3"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
