name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "382070e9565e1ad77a84b8f250cab33416a6b5b8d95ce6840977ba5f515d40ad"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
