name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d179ef9e4e4ba0f7779c2a68dac173a96f8c0e2af78d7f2fb8aefac1b0d5133"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
