name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c3020863c0ed63df8ec28bffc98e46d0854baf816ce4c1ea33a4f39c3fcf86a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
