name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab76f3de97b9c06d38523595adfa645d4e18f2d7ed8b1b22d06f655ad78ca27"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
