name = "CraftBOX.pl"
author = "CraftBOX Dev Team"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b38a386cbc3b11156d1648de51026830a370b2ea517c1b5f65e75bf5ecef48b3"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
