DRIED_GOLDEN_KELP_TOGGLE = true
COOKED_GOLDEN_SALMON_TOGGLE = true
COOKED_GOLDEN_COD_TOGGLE = true
GOLDEN_TURTLE_EGG_TOGGLE = true
COOKED_GOLDEN_CHICKEN_TOGGLE = true
GOLDEN_BEETROOT_TOGGLE = true
GOLDEN_BEETROOT_SOUP_TOGGLE = true
GOLDEN_CHORUS_FRUIT_TOGGLE = true
POISONOUS_GOLDEN_POTATO_TOGGLE = true
BAKED_GOLDEN_POTATO_TOGGLE = true
COOKED_GOLDEN_MUTTON_TOGGLE = true
COOKED_GOLDEN_PORKCHOP_TOGGLE = true
COOKED_GOLDEN_RABBIT_TOGGLE = true
COOKED_GOLDEN_BEEF_TOGGLE = true
SWEET_GOLDEN_BERRIES_TOGGLE = true
VILLAGER_OFFERS_GOLDEN_BEETROOT = true
VILLAGER_OFFERS_DRIED_GOLDEN_KELP = true
VILLAGER_OFFERS_COOKED_GOLDEN_COD = true
VILLAGER_OFFERS_POISONOUS_GOLDEN_POTATO = true
VILLAGER_OFFERS_COOKED_GOLDEN_CHICKEN = true
VILLAGER_OFFERS_BAKED_GOLDEN_POTATO = true
VILLAGER_OFFERS_COOKED_GOLDEN_MUTTON = true
VILLAGER_OFFERS_COOKED_GOLDEN_PORKCHOP = true
VILLAGER_OFFERS_COOKED_GOLDEN_RABBIT = true
VILLAGER_OFFERS_COOKED_GOLDEN_BEEF = true
