name = "Beacon Overhaul"
filename = "BeaconOverhaul-1.3.1+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3240/614/BeaconOverhaul-1.3.1+1.16.jar"
hash-format = "murmur2"
hash = "3035968383"

[update]
[update.curseforge]
file-id = 3240614
project-id = 430382
release-channel = "beta"
