name = "BetterSleepPlus"
filename = "bettersleepplus-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3203/739/bettersleepplus-2.4.0.jar"
hash-format = "murmur2"
hash = "3530102401"

[update]
[update.curseforge]
file-id = 3203739
project-id = 423469
release-channel = "beta"
