name = "Better World Border"
filename = "BetterWorldBorder-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3177/708/BetterWorldBorder-1.0.0.jar"
hash-format = "murmur2"
hash = "1327993339"

[update]
[update.curseforge]
file-id = 3177708
project-id = 438957
release-channel = "beta"
