name = "Better Ping Display [Fabric]"
filename = "BetterPingDisplay-Fabric-1.16.4-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3103/492/BetterPingDisplay-Fabric-1.16.4-1.1.jar"
hash-format = "murmur2"
hash = "674768865"

[update]
[update.curseforge]
file-id = 3103492
project-id = 406343
release-channel = "beta"
