name = "Bobby"
filename = "bobby-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/733/bobby-1.1.1.jar"
hash-format = "murmur2"
hash = "612747101"

[update]
[update.curseforge]
file-id = 3245733
project-id = 409301
release-channel = "beta"
