name = "ClickThrough"
filename = "clickthrough-1.16.5-fabric0.30.0-0.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3233/414/clickthrough-1.16.5-fabric0.30.0-0.4.jar"
hash-format = "murmur2"
hash = "4052482319"

[update]
[update.curseforge]
file-id = 3233414
project-id = 405262
release-channel = "beta"
