name = "Color Unchained"
filename = "colorunchained-1.1.1-1.16.4.jar"
side = "client"

[option]
optional = false
description = "GUI for picking colors"
default = true

[download]
url = "https://edge.forgecdn.net/files/3109/879/colorunchained-1.1.1-1.16.4.jar"
hash-format = "murmur2"
hash = "1358823898"

[update]
[update.curseforge]
file-id = 3109879
project-id = 391781
release-channel = "beta"
