name = "Connectible Chains"
filename = "connectiblechains-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3102/125/connectiblechains-1.1.0.jar"
hash-format = "murmur2"
hash = "671690317"

[update]
[update.curseforge]
file-id = 3102125
project-id = 415681
release-channel = "beta"
