name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.16.4-FORGE-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/315/Croptopia-1.16.4-FORGE-1.3.1.jar"
hash-format = "murmur2"
hash = "1697111021"

[update]
[update.curseforge]
file-id = 3245315
project-id = 415438
release-channel = "beta"
