name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.16.4-5-FABRIC-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/314/Croptopia-1.16.4-5-FABRIC-1.3.1.jar"
hash-format = "murmur2"
hash = "4083224907"

[update]
[update.curseforge]
file-id = 3245314
project-id = 415438
release-channel = "beta"
