name = "Customizable Elytra (Fabric)"
filename = "customizableelytra-fabric-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/118/customizableelytra-fabric-1.1.0.jar"
hash-format = "murmur2"
hash = "1572222563"

[update]
[update.curseforge]
file-id = 3243118
project-id = 448274
release-channel = "beta"
