name = "Damage Tint"
filename = "damage-tint-forge-1.16.5-1.0.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3203/478/damage-tint-forge-1.16.5-1.0.1.jar"
hash-format = "murmur2"
hash = "3568950490"

[update]
[update.curseforge]
file-id = 3203478
project-id = 434182
release-channel = "beta"
