name = "Dawn API"
filename = "dawn-1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/550/dawn-1.7.jar"
hash-format = "murmur2"
hash = "1052027527"

[update]
[update.curseforge]
file-id = 3213550
project-id = 399309
release-channel = "beta"
