name = "Enhanced Attack Indicator"
filename = "enhanced_attack_indicator-1.0.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3201/935/enhanced_attack_indicator-1.0.0+1.16.jar"
hash-format = "murmur2"
hash = "1738165635"

[update]
[update.curseforge]
file-id = 3201935
project-id = 446173
release-channel = "beta"
