name = "Experience Container [XP]"
filename = "Experience-Container-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3187/691/Experience-Container-1.12.jar"
hash-format = "murmur2"
hash = "1374523232"

[update]
[update.curseforge]
file-id = 3187691
project-id = 327525
release-channel = "beta"
