name = "Fabric Console"
filename = "fabric-console-1.0.3+1.16.3.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3062/13/fabric-console-1.0.3+1.16.3.jar"
hash-format = "murmur2"
hash = "3651872303"

[update]
[update.curseforge]
file-id = 3062013
project-id = 382518
release-channel = "beta"
