name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.5.0+1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3183/593/fallingleaves-1.5.0+1.16.5.jar"
hash-format = "murmur2"
hash = "2222666032"

[update]
[update.curseforge]
file-id = 3183593
project-id = 417510
release-channel = "beta"
