name = "Fireplace Lib"
filename = "Fireplace-Lib-3.1.0+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3228/725/Fireplace-Lib-3.1.0+1.16.5.jar"
hash-format = "murmur2"
hash = "721586534"

[update]
[update.curseforge]
file-id = 3228725
project-id = 432845
release-channel = "beta"
