name = "Illuminations 🔥"
filename = "illuminations-1.4.6.jar"
side = "client"

[option]
optional = true
description = "A client mod that adds fireflies and various glow-in-the-dark ambient particles to your world."
default = true

[download]
url = "https://edge.forgecdn.net/files/3238/442/illuminations-1.4.6.jar"
hash-format = "murmur2"
hash = "3541275576"

[update]
[update.curseforge]
file-id = 3238442
project-id = 292908
release-channel = "beta"
