name = "[FABRIC] Iron Furnaces"
filename = "ironfurnaces-1.16-2.4.1.jar"
side = "both"

[download]
url = "https://github.com/CraftBoxPL/craftbox-server-pack/raw/master/mods/jars/ironfurnaces-1.16-2.4.1.jar"
hash-format = "sha256"
hash = "d3de54476a7284f650a3425f74f964bdb7231665b87dd3abc0235ab074e098db"

[update]
[update.curseforge]
file-id = 3181191
project-id = 318036
release-channel = "beta"
