name = "[FABRIC] Iron Furnaces"
filename = "[FABRIC]%20ironfurnaces-1.16-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3181/191/[FABRIC]%20ironfurnaces-1.16-2.4.1.jar"
hash-format = "murmur2"
hash = "2688275782"

[update]
[update.curseforge]
file-id = 3181191
project-id = 318036
release-channel = "beta"
