name = "[FORGE] Iron Furnaces"
filename = "ironfurnaces-1.16.5-2.6.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/254/ironfurnaces-1.16.5-2.6.5.jar"
hash-format = "murmur2"
hash = "1789581573"

[update]
[update.curseforge]
file-id = 3245254
project-id = 237664
release-channel = "beta"
