name = "Konkrete [Fabric]"
filename = "konkrete_fabric_1.1.3_MC_1.16.3-1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3191/489/konkrete_fabric_1.1.3_MC_1.16.3-1.16.5.jar"
hash-format = "murmur2"
hash = "1420340364"

[update]
[update.curseforge]
file-id = 3191489
project-id = 416797
release-channel = "beta"
