name = "Lightstones"
filename = "lightstones-1.3.0-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3185/965/lightstones-1.3.0-forge.jar"
hash-format = "murmur2"
hash = "526221473"

[update]
[update.curseforge]
file-id = 3185965
project-id = 368263
release-channel = "beta"
