name = "MiniMOTD"
filename = "minimotd-fabric-mc1.16.5-2.0.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3204/407/minimotd-fabric-mc1.16.5-2.0.0.jar"
hash-format = "murmur2"
hash = "1721724178"

[update]
[update.curseforge]
file-id = 3204407
project-id = 399892
release-channel = "beta"
