name = "More Berries"
filename = "moreberries-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3116/717/moreberries-1.3.4.jar"
hash-format = "murmur2"
hash = "1426286841"

[update]
[update.curseforge]
file-id = 3116717
project-id = 315749
release-channel = "beta"
