name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.6.4+mc1.16.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3193/582/mousewheelie-1.6.4+mc1.16.4.jar"
hash-format = "murmur2"
hash = "2635997553"

[update]
[update.curseforge]
file-id = 3193582
project-id = 317514
release-channel = "beta"
