name = "Potion of Bees: Fabric Edition"
filename = "potionofbees-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3052/244/potionofbees-1.0.2.jar"
hash-format = "murmur2"
hash = "3571390277"

[update]
[update.curseforge]
file-id = 3052244
project-id = 356673
release-channel = "beta"
