name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures-1.16.5-1.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3239/765/repurposed_structures-1.16.5-1.9.0.jar"
hash-format = "murmur2"
hash = "899876735"

[update]
[update.curseforge]
file-id = 3239765
project-id = 391366
release-channel = "beta"
