name = "Eric's Retail"
filename = "Retail-mc1.16-fabric-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3183/519/Retail-mc1.16-fabric-0.1.1.jar"
hash-format = "murmur2"
hash = "2799961164"

[update]
[update.curseforge]
file-id = 3183519
project-id = 431323
release-channel = "beta"
