name = "RPG-Hud [Fabric]"
filename = "[1.16.2][Fabric] RPG-HUD-3.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3047/749/[1.16.2][Fabric] RPG-HUD-3.8.1.jar"
hash-format = "murmur2"
hash = "3297075291"

[update]
[update.curseforge]
file-id = 3047749
project-id = 397179
release-channel = "beta"
