name = "RPG-Hud [Fabric]"
filename = "RPG-HUD-3.8.1.jar"
side = "client"

[download]
url = "https://github.com/CraftBoxPL/craftbox-server-pack/raw/master/mods/jars/RPG-HUD-3.8.1.jar"
hash-format = "sha256"
hash = "30ff1e3578ccb64666f2588446a90338a0232f58f3b10e5aad11422b0d77efb2"

[update]
[update.curseforge]
file-id = 3047749
project-id = 397179
release-channel = "beta"
