name = "Seamless Loading Screen "
filename = "seamless-loading-screen-1.3.2+1.16.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/TyTPFOiF/versions/v1.3.2+1.16/seamless-loading-screen-1.3.2+1.16.2.jar"
hash-format = "sha512"
hash = "997a8c1be69381acf2232ca8d839f4d8c1cb8a919272afac0c80c9b65594fde3c7b77200afd978c1a23f417e4be997cbbfb3244dfd03842ce077562a5d7d1bd1"

[update]
[update.modrinth]
mod-id = "TyTPFOiF"
version = "KSWQCNKT"
