name = "Wither Skeleton Totem"
filename = "Wither-Totems-Mod-0.3.2-1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/936/Wither-Totems-Mod-0.3.2-1.16.2.jar"
hash-format = "murmur2"
hash = "456588921"

[update]
[update.curseforge]
file-id = 3124936
project-id = 349850
release-channel = "beta"
