name = "WorldEdit CUI (Fabric)"
filename = "WorldEditCUI-1.16.5+02.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3196/964/WorldEditCUI-1.16.5+02.jar"
hash-format = "murmur2"
hash = "36391570"

[update]
[update.curseforge]
file-id = 3196964
project-id = 402098
release-channel = "beta"
