name = "WorldEdit"
filename = "worldedit-mod-7.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3237/691/worldedit-mod-7.2.4.jar"
hash-format = "murmur2"
hash = "3270480908"

[update]
[update.curseforge]
file-id = 3237691
project-id = 225608
release-channel = "beta"
